pipeline {
    agent any

    stages {

        stage("Unit Test - Backend") {
            agent {
                docker {
                    image 'golang:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = "${WORKSPACE}/.gocache"
            }
            steps {
                sh 'mkdir -p $GOCACHE'

                dir("bugtracker-backend") {
                    sh 'go test -v ./...'
                }
            }
        }

        stage("Unit Test - Frontend") {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            environment {
                NPM_CONFIG_CACHE = "${WORKSPACE}/.npm"
            }
            steps {
                sh 'mkdir -p $NPM_CONFIG_CACHE'
                dir("bugtracker-frontend") {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
        }

    }
}
